version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages
    working_dir: /app
